# Generated by Django 4.2.20 on 2025-07-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_item_image_url_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='payment_intent_id',
            field=models.CharField(blank=True, help_text='Stripe payment intent ID', max_length=255, null=True),
        ),
    ]
