# Generated by Django 4.2.20 on 2025-07-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_purchase_payment_intent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('accessories', 'Accessories'), ('bags', 'Bags'), ('shoes', 'Shoes'), ('sunglasses', 'Sunglasses')], default='clothing', max_length=20),
        ),
    ]
