# Generated by Django 4.2.20 on 2025-07-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price in EUR (Euro)', max_digits=10),
        ),
    ]
